### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by rossman22590**
Added docker yay!

### CODE REVIEW

**Comment by ioanmo226** [comment]
Thank you for your contribution! 

Would it be possible for you to also add documentation on how to set up Docker in the README file? It would be great if you could provide guidance on how to handle the .env file and set up the Docker image. An example command to run the Docker container could be `docker run -p 3001:3001 -e OPENAI_API_KEY=your_api_key`

**Comment by rossman22590** [comment]
Do you use Railway?

**Comment by ioanmo226** [comment]
No

**Comment by rossman22590** [comment]
So you can still use the env file, docker just helps it install on serverless platforms like railway.  https://railway.app/

**Comment by ioanmo226** [comment]
Sounds good!

**Comment by rossman22590** [comment]
Steps to launch 

1. Go to https://railway.app/
2. Then Create project linked to GitHub
3. Edit ENV in Railway variables:

```
OPENAI_API_KEY=your key here
PORT=3001
```
That's it! :)

**Pull request merged**
